-- EXERCISE 1
SELECT COUNT(*) AS DUPLICATED_COMPANIES 
FROM
  (SELECT COMPANY_ID, TITLE, DESCRIPTION
  FROM JOB_LISTINGS
  GROUP BY COMPANY_ID, TITLE, DESCRIPTION
  HAVING COUNT(*) > 1) AS DUPLICATED_JOBS_PER_COMPANY;

-- EXERCISE 2
WITH RANKED_PRODUCTS
AS
  (SELECT CATEGORY, PRODUCT,
  SUM(SPEND) AS TOTAL_SPEND
  FROM PRODUCT_SPEND
  WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = 2022
  GROUP BY CATEGORY, PRODUCT
  ORDER BY TOTAL_SPEND DESC)
SELECT CATEGORY, PRODUCT, TOTAL_SPEND
FROM RANKED_PRODUCTS
  

-- EXERCISE 3

-- EXERCISE 4

-- EXERCISE 5

-- EXERCISE 6

-- EXERCISE 7

-- EXERCISE 8

-- EXERCISE 9

-- EXERCISE 10

-- EXERCISE 11

-- EXERCISE 12

--
